# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, amqp, clock, configurator, ekg, filepath, hinotify
, hslogger, optparseApplicative, text
}:

cabal.mkDerivation (self: {
  pname = "amqp-pathwatcher";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [
    amqp clock configurator ekg filepath hinotify hslogger
    optparseApplicative text
  ];
  meta = {
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
